import React, { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material';
import DataTable, { DataRow } from './DataTable';
import DataCharts from './DataCharts';
import api from '../api/axios';

const money=(v:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v);
export default function Dashboard(){
  const [metrics,setMetrics]=useState<any>({}); const [alerts,setAlerts]=useState<any[]>([]); const [scenario,setScenario]=useState(''); const [scenarioData,setScenarioData]=useState<any[]>([]); const [chartRows,setChartRows]=useState<DataRow[]>([]); const [importInfo,setImportInfo]=useState<any>(null);
  const load=async()=>{try{const [o,a]=await Promise.all([api.get('/analytics/overview'),api.get('/analytics/alerts')]);setMetrics(o.data.metrics||{});setImportInfo(o.data.import);setAlerts(a.data.data||[]);setChartRows((o.data.topActivities||[]).map((r:any,i:number)=>({id:String(i),код_окэд:r.oked,вид_деятельности:r.activity,средняя_численность_работников:Number(r.employees||0),'Сумма по полю ФОТ':Number(r.payroll||0),Сумма_по_полю_ср_зп:Number(r.average_salary||0),сумма_налогов:Number(r.taxes||0),удельный_вес:0}))); }catch(e){console.error(e)}};
  useEffect(()=>{load()},[]);
  const runScenario=async(name:string)=>{setScenario(name);const r=await api.get('/analytics/scenarios',{params:{scenario:name}});setScenarioData(r.data.data||[])};
  return <Box sx={{p:{xs:1,md:2}}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} sx={{mb:2}}><Box><Typography variant="h4" fontWeight={900}>Панель eFOT</Typography><Typography color="text.secondary">От показателей к отклонениям и решениям</Typography></Box><Typography variant="body2" color="text.secondary">{importInfo?`Набор: ${importInfo.period||'без периода'} · ${importInfo.territory||'территория не указана'}`:'Данные ещё не загружены'}</Typography></Stack>
    <Grid container spacing={2} sx={{mb:2}}>{[['Организации',metrics.organizations||0],['Работники',metrics.employees||0],['ФОТ',metrics.payroll||0],['Средняя ЗП',metrics.averageSalary||0],['Налоги',metrics.taxes||0]].map(([label,value],i)=><Grid item xs={12} sm={6} md={2.4} key={String(label)}><Card><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h5" fontWeight={900}>{money(Number(value))}{i>1?' ₸':''}</Typography></CardContent></Card></Grid>)}</Grid>
    <Card sx={{mb:2}}><CardContent><Typography fontWeight={900} sx={{mb:1}}>Сценарии проверки</Typography><Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap><Button size="small" variant="outlined" onClick={()=>runScenario('high_payroll')}>Высокий ФОТ</Button><Button size="small" variant="outlined" onClick={()=>runScenario('high_salary')}>Высокая ЗП</Button><Button size="small" variant="outlined" onClick={()=>runScenario('low_salary')}>Низкая ЗП</Button><Button size="small" variant="outlined" onClick={()=>runScenario('low_workforce')}>Малая численность</Button><Button size="small" variant="outlined" onClick={()=>runScenario('tax_zero')}>ФОТ без налогов</Button></Stack>{scenario&&<Box sx={{mt:2}}><Typography fontWeight={700}>Результат: {scenarioData.length}</Typography>{scenarioData.slice(0,5).map((r,i)=><Box key={i} sx={{py:1,borderBottom:'1px solid #eee'}}><b>{r.oked}</b> — {r.activity} · ФОТ {money(Number(r.payroll||0))}</Box>)}</Box>}</CardContent></Card>
    {alerts.length>0&&<Card sx={{mb:2}}><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={900}>Автоматические сигналы</Typography><Chip label={`${alerts.length} найдено`} color="warning" size="small"/></Stack>{alerts.slice(0,6).map((a,i)=><Alert key={i} severity={a.risk==='high'?'error':'warning'} sx={{mt:1}}><b>{a.company_name||a.activity}</b>: {a.factors?.join('; ')}</Alert>)}</CardContent></Card>}
    <DataCharts data={chartRows}/><DataTable />
  </Box>;
}
