import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { DataGrid, GridColDef, GridRowSelectionModel } from '@mui/x-data-grid';
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Paper, Stack, TextField, Tooltip, Typography } from '@mui/material';
import FilterListIcon from '@mui/icons-material/FilterList';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import SearchIcon from '@mui/icons-material/Search';
import UploadFileIcon from '@mui/icons-material/UploadFile';
import api from '../api/axios';
import ExportButtons from './ExportButtons';
import { useAuth } from '../contexts/AuthContext';

export interface DataRow { id:string; код_окэд:string; вид_деятельности:string; средняя_численность_работников:number; ['Сумма по полю ФОТ']:number; Сумма_по_полю_ср_зп:number; сумма_налогов:number; удельный_вес:number; period_label?:string; territory?:string; }
interface Filters { q:string; oked:string; activity:string; period:string; territory:string; employeesMin:string; employeesMax:string; payrollMin:string; payrollMax:string; salaryMin:string; salaryMax:string; taxesMin:string; taxesMax:string; }
const empty:Filters={q:'',oked:'',activity:'',period:'',territory:'',employeesMin:'',employeesMax:'',payrollMin:'',payrollMax:'',salaryMin:'',salaryMax:'',taxesMin:'',taxesMax:''};

export default function DataTable({ onRowsChange }: { onRowsChange?: (rows:DataRow[])=>void }) {
  const {isAdmin}=useAuth(); const [company,setCompany]=useState<any>(null); const [companyOpen,setCompanyOpen]=useState(false); const [rows,setRows]=useState<DataRow[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(0); const [pageSize,setPageSize]=useState(25); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [filters,setFilters]=useState(empty); const [draft,setDraft]=useState(empty); const [filterOpen,setFilterOpen]=useState(false); const [selection,setSelection]=useState<GridRowSelectionModel>([]); const [related,setRelated]=useState<any[]>([]); const [relatedTitle,setRelatedTitle]=useState(''); const [relatedOpen,setRelatedOpen]=useState(false); const [uploading,setUploading]=useState(false);

  const params=useMemo(()=>Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=='')),[filters]);
  const load=useCallback(async()=>{ setLoading(true);setError(''); try { const r=await api.get('/data',{params:{...params,page:page+1,pageSize}}); setRows(r.data.data||[]);setTotal(r.data.total||0);onRowsChange?.(r.data.data||[]); } catch(e:any){setError(e.response?.data?.message||'Ошибка загрузки данных');} finally{setLoading(false);} }, [page, pageSize, params, onRowsChange]);
  useEffect(()=>{load();},[load]);
  const apply=()=>{setPage(0);setFilters(draft);setFilterOpen(false);};
  const reset=()=>{setPage(0);setDraft(empty);setFilters(empty);setFilterOpen(false);};
  const openCompany=async(bin:string)=>{try{const r=await api.get(`/companies/${encodeURIComponent(bin)}`);setCompany(r.data);setCompanyOpen(true)}catch(e:any){setError(e.response?.data?.message||'Профиль компании недоступен')}};
  const relatedData=async(activity:string)=>{try{const r=await api.get(`/related-data/${encodeURIComponent(activity)}`);setRelated(r.data);setRelatedTitle(activity);setRelatedOpen(true);}catch(e:any){setError(e.response?.data?.message||'Не удалось открыть детализацию');}};
  const autoImport=async(file:File)=>{setUploading(true);try{const fd=new FormData();fd.append('file',file);const r=await api.post('/import/auto',fd,{headers:{'Content-Type':'multipart/form-data'}});alert(`${r.data.message}\nТип: ${r.data.datasetType}\nСтрок: ${r.data.rows}`);setPage(0);await load();}catch(e:any){alert(e.response?.data?.message||'Ошибка импорта');}finally{setUploading(false);}};
  const columns:GridColDef[]= [
    {field:'actions',headerName:'',width:55,sortable:false,renderCell:p=><Tooltip title="Детализация"><IconButton onClick={()=>relatedData(p.row.вид_деятельности)}><InfoOutlinedIcon/></IconButton></Tooltip>},
    {field:'код_окэд',headerName:'ОКЭД',width:90},{field:'вид_деятельности',headerName:'Вид деятельности',flex:1,minWidth:300},
    {field:'средняя_численность_работников',headerName:'Работники',width:120,type:'number',valueFormatter:p=>Number(p.value||0).toLocaleString('ru-RU')},
    {field:'Сумма по полю ФОТ',headerName:'ФОТ',width:150,type:'number',valueFormatter:p=>Number(p.value||0).toLocaleString('ru-RU')},
    {field:'Сумма_по_полю_ср_зп',headerName:'Средняя ЗП',width:135,type:'number',valueFormatter:p=>Number(p.value||0).toLocaleString('ru-RU')},
    {field:'сумма_налогов',headerName:'Налоги',width:140,type:'number',valueFormatter:p=>Number(p.value||0).toLocaleString('ru-RU')},
    {field:'удельный_вес',headerName:'Доля, %',width:100,type:'number',valueFormatter:p=>`${Number(p.value||0).toFixed(2)}%`},
  ];
  return <Box sx={{p:{xs:1,md:2}}}>
    <Paper sx={{p:2,mb:2}}><Stack direction={{xs:'column',md:'row'}} spacing={1.5} alignItems={{md:'center'}}><TextField size="small" fullWidth placeholder="Поиск по ОКЭД или виду деятельности" value={filters.q} onChange={e=>{setPage(0);setFilters({...filters,q:e.target.value})}} InputProps={{startAdornment:<SearchIcon sx={{mr:1,color:'text.secondary'}}/>}}/><Button variant="outlined" startIcon={<FilterListIcon/>} onClick={()=>setFilterOpen(true)}>Умные фильтры</Button>{isAdmin&&<Button component="label" variant="contained" startIcon={<UploadFileIcon/>} disabled={uploading}>{uploading?'Загрузка…':'Загрузить Excel'}<input hidden type="file" accept=".xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)autoImport(f);e.currentTarget.value=''}}/></Button>}<ExportButtons ids={selection.map(String)}/></Stack>{error&&<Alert sx={{mt:2}} severity="error">{error}</Alert>}</Paper>
    <Paper sx={{height:650}}><DataGrid rows={rows} columns={columns} loading={loading} rowCount={total} paginationMode="server" paginationModel={{page,pageSize}} onPaginationModelChange={m=>{setPage(m.page);setPageSize(m.pageSize)}} pageSizeOptions={[25,50,100,200]} checkboxSelection disableRowSelectionOnClick onRowSelectionModelChange={setSelection}/></Paper>
    <Dialog open={filterOpen} onClose={()=>setFilterOpen(false)} maxWidth="md" fullWidth><DialogTitle>Умные фильтры</DialogTitle><DialogContent><Grid container spacing={2} sx={{pt:1}}>{[['oked','ОКЭД'],['activity','Вид деятельности'],['period','Период'],['territory','Территория'],['employeesMin','Мин. работников'],['employeesMax','Макс. работников'],['payrollMin','Мин. ФОТ'],['payrollMax','Макс. ФОТ'],['salaryMin','Мин. средняя ЗП'],['salaryMax','Макс. средняя ЗП'],['taxesMin','Мин. налоги'],['taxesMax','Макс. налоги']].map(([key,label])=><Grid item xs={12} sm={6} key={key}><TextField fullWidth size="small" label={label} value={(draft as any)[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} type={key.includes('Min')||key.includes('Max')?'number':'text'}/></Grid>)}</Grid></DialogContent><DialogActions><Button onClick={reset}>Сбросить</Button><Button variant="contained" onClick={apply}>Применить</Button></DialogActions></Dialog>
    <Dialog open={relatedOpen} onClose={()=>setRelatedOpen(false)} maxWidth="xl" fullWidth><DialogTitle>Детализация: {relatedTitle}</DialogTitle><DialogContent><Typography color="text.secondary" sx={{mb:1}}>Показаны записи последнего детального импорта. Это детализация, а не автоматическое заключение о компании.</Typography><Box sx={{overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['ОКЭД','ИИН/БИН','Наименование','Численность','ФОТ','Средняя ЗП','Налоги'].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:'1px solid #ddd'}}>{h}</th>)}</tr></thead><tbody>{related.map((r,i)=><tr key={r.id||i}><td style={{padding:8,borderBottom:'1px solid #eee'}}>{r['Код ОКЭД'] ?? '—'}</td><td style={{padding:8,borderBottom:'1px solid #eee'}}>{r['ИИН/БИН'] ? <Button size="small" onClick={()=>openCompany(String(r['ИИН/БИН']))}>{r['ИИН/БИН']}</Button> : '—'}</td>{['Наименование','Ср.числ','ФОТ','Ср.зп','Налоги'].map(k=><td key={k} style={{padding:8,borderBottom:'1px solid #eee'}}>{r[k] ?? '—'}</td>)}</tr>)}</tbody></table></Box></DialogContent><DialogActions><Button onClick={()=>setRelatedOpen(false)}>Закрыть</Button></DialogActions></Dialog>
    <Dialog open={companyOpen} onClose={()=>setCompanyOpen(false)} maxWidth="md" fullWidth><DialogTitle>Профиль компании</DialogTitle><DialogContent>{company&&<><Typography variant="h6" fontWeight={800}>{company.company?.name||'Без названия'}</Typography><Typography color="text.secondary">БИН/ИИН: {company.company?.bin}</Typography><Grid container spacing={2} sx={{my:1}}>{[['Риск',company.riskScore],['Работники',company.current?.employees],['ФОТ',company.current?.payroll],['Средняя ЗП',company.current?.averageSalary],['Налоги',company.current?.taxes]].map(([k,v])=><Grid item xs={6} sm={4} key={String(k)}><Paper sx={{p:1.5}}><Typography variant="caption" color="text.secondary">{k}</Typography><Typography fontWeight={800}>{typeof v==='number'?Number(v).toLocaleString('ru-RU'):v}</Typography></Paper></Grid>)}</Grid><Typography fontWeight={800} sx={{mt:2}}>Сигналы</Typography>{company.riskFactors?.length?company.riskFactors.map((f:any)=><Alert key={f.code} severity={f.severity==='high'?'error':'warning'} sx={{mt:1}}>{f.message}</Alert>):<Alert severity="success">Критичных автоматических сигналов не обнаружено.</Alert>}<Typography fontWeight={800} sx={{mt:2}}>История</Typography>{company.history?.map((h:any,i:number)=><Box key={i} sx={{py:1,borderBottom:'1px solid #eee'}}>{h.period||'Период не указан'} · работников {Number(h.employees||0).toLocaleString('ru-RU')} · ФОТ {Number(h.payroll||0).toLocaleString('ru-RU')}</Box>)}</>}</DialogContent><DialogActions><Button onClick={()=>setCompanyOpen(false)}>Закрыть</Button></DialogActions></Dialog>
  </Box>;
}
