import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { DataGrid, GridColDef, GridRowSelectionModel } from '@mui/x-data-grid';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Paper, Stack, TextField, Tooltip, Typography } from '@mui/material';
import FilterListIcon from '@mui/icons-material/FilterList';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import SearchIcon from '@mui/icons-material/Search';
import api from '../api/axios';
import ExportButtons from './ExportButtons';
import HistoryCharts, { formatMetric, metricLabels } from './HistoryCharts';

export interface DataRow { id:string; код_окэд:string; вид_деятельности:string; средняя_численность_работников:number; ['Сумма по полю ФОТ']:number; Сумма_по_полю_ср_зп:number; сумма_налогов:number; удельный_вес:number; period_label?:string; territory?:string; }
interface Filters { q:string; oked:string; activity:string; period:string; territory:string; employeesMin:string; employeesMax:string; payrollMin:string; payrollMax:string; salaryMin:string; salaryMax:string; taxesMin:string; taxesMax:string; }
const empty:Filters={q:'',oked:'',activity:'',period:'',territory:'',employeesMin:'',employeesMax:'',payrollMin:'',payrollMax:'',salaryMin:'',salaryMax:'',taxesMin:'',taxesMax:''};

export default function DataTable({ onRowsChange, importId, datasetType, onImported }: { onRowsChange?: (rows:DataRow[])=>void; importId?: string; datasetType?: string; onImported?: (id?:string,message?:string)=>Promise<void> }) {
  const [company,setCompany]=useState<any>(null); const [companyOpen,setCompanyOpen]=useState(false); const [rows,setRows]=useState<DataRow[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(0); const [pageSize,setPageSize]=useState(25); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [filters,setFilters]=useState(empty); const [draft,setDraft]=useState(empty); const [filterOpen,setFilterOpen]=useState(false); const [selection,setSelection]=useState<GridRowSelectionModel>([]); const [related,setRelated]=useState<any[]>([]); const [relatedTitle,setRelatedTitle]=useState(''); const [relatedOpen,setRelatedOpen]=useState(false);

  const params=useMemo(()=>({...Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=='')), ...(importId ? {importId} : {})}),[filters,importId]);
  const load=useCallback(async()=>{ setLoading(true);setError(''); try { if (!importId) { setRows([]);setTotal(0);return; } const r=await api.get('/data',{params:{...params,page:page+1,pageSize}}); setRows(r.data.data||[]);setTotal(r.data.total||0);onRowsChange?.(r.data.data||[]); } catch(e:any){setError(e.response?.data?.message||'Ошибка загрузки данных');} finally{setLoading(false);} }, [page, pageSize, params, onRowsChange, importId]);
  useEffect(()=>{load();},[load]);
  const apply=()=>{setPage(0);setSelection([]);setFilters(draft);setFilterOpen(false);};
  const reset=()=>{setPage(0);setSelection([]);setDraft(empty);setFilters(empty);setFilterOpen(false);};
  const openCompany=async(bin:string)=>{try{const r=await api.get(`/companies/${encodeURIComponent(bin)}`,{params:{importId}});setCompany(r.data);setCompanyOpen(true)}catch(e:any){setError(e.response?.data?.message||'Профиль компании недоступен')}};
  const relatedData=async(activity:string)=>{try{const r=await api.get(`/related-data/${encodeURIComponent(activity)}`,{params:{importId}});setRelated(r.data);setRelatedTitle(activity);setRelatedOpen(true);}catch(e:any){setError(e.response?.data?.message||'Не удалось открыть детализацию');}};
  const columns:GridColDef[]= [
    {field:'actions',headerName:'',width:55,sortable:false,renderCell:p=><Tooltip title="Детализация"><IconButton aria-label="Открыть подробности" onClick={()=>p.row.company_bin?openCompany(p.row.company_bin):relatedData(p.row.вид_деятельности)}><InfoOutlinedIcon/></IconButton></Tooltip>},
    ...(datasetType==='detail' ? [{field:'company_bin',headerName:'БИН/ИИН',width:145},{field:'company_name',headerName:'Компания',width:320}] : []),
    {field:'код_окэд',headerName:'ОКЭД',width:90},{field:'вид_деятельности',headerName:'Вид деятельности',flex:1,minWidth:300},
    {field:'средняя_численность_работников',headerName:'Работники',width:120,type:'number',valueFormatter:p=>formatMetric(p.value)},
    {field:'Сумма по полю ФОТ',headerName:'ФОТ',width:150,type:'number',valueFormatter:p=>formatMetric(p.value)},
    {field:'Сумма_по_полю_ср_зп',headerName:'Средняя ЗП',width:135,type:'number',valueFormatter:p=>formatMetric(p.value)},
    {field:'сумма_налогов',headerName:'Налоги',width:140,type:'number',valueFormatter:p=>formatMetric(p.value)},
    {field:'удельный_вес',headerName:'Доля, %',width:100,type:'number',valueFormatter:p=>`${Number(p.value||0).toFixed(2)}%`},
  ];
  return <Box sx={{p:{xs:1,md:2}}}>
    <Paper variant="outlined" sx={{p:{xs:2,md:3},mb:2,borderRadius:3}}>
      <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{mb:2}}><Box><Typography variant="h6" fontWeight={800}>Данные и отчеты</Typography><Typography variant="body2" color="text.secondary">Найдите нужные записи и скачайте отчет.</Typography></Box><Chip label={'Найдено: '+total.toLocaleString('ru-RU')} variant="outlined"/></Stack>
      <Stack direction={{xs:'column',md:'row'}} spacing={1.5} sx={{mb:2}}>
        <TextField size="small" fullWidth label="Поиск" placeholder="Компания, БИН или вид деятельности" value={filters.q} onChange={e=>{setPage(0);setSelection([]);setFilters({...filters,q:e.target.value})}} InputProps={{startAdornment:<SearchIcon sx={{mr:1,color:'text.secondary'}}/>}}/>
        <Button variant="outlined" startIcon={<FilterListIcon/>} onClick={()=>{setDraft(filters);setFilterOpen(true)}}>Фильтры</Button>
        {Object.values(filters).some(Boolean)&&<Button onClick={reset}>Сбросить</Button>}
      </Stack>
      <ExportButtons ids={selection.map(String)} importId={importId} filters={params} total={total}/>
      {error&&<Alert sx={{mt:2}} severity="error" onClose={()=>setError('')}>{error}</Alert>}
    </Paper>
    <Paper sx={{height:650}}><DataGrid rows={rows} columns={columns} loading={loading} rowCount={total} paginationMode="server" paginationModel={{page,pageSize}} onPaginationModelChange={m=>{setPage(m.page);setPageSize(m.pageSize)}} pageSizeOptions={[25,50,100,200]} checkboxSelection disableRowSelectionOnClick rowSelectionModel={selection} keepNonExistentRowsSelected onRowSelectionModelChange={setSelection}
      localeText={{noRowsLabel:importId?'В этом наборе нет строк. Измените фильтры.':'Загрузите Excel или выберите набор данных выше.',noResultsOverlayLabel:'Ничего не найдено. Попробуйте другой запрос.',footerRowSelected:count=>'Выбрано строк: '+count,MuiTablePagination:{labelRowsPerPage:'Строк на странице:',labelDisplayedRows:({from,to,count})=>`${from}–${to} из ${count}`}}}
      sx={{border:0,'& .MuiDataGrid-columnHeaders':{bgcolor:'#edf3f8'},'& .MuiDataGrid-cell:focus':{outline:'2px solid #0b7590'}}}/></Paper>
    <Dialog open={filterOpen} onClose={()=>setFilterOpen(false)} maxWidth="md" fullWidth><DialogTitle>Фильтры данных</DialogTitle><DialogContent><Grid container spacing={2} sx={{pt:1}}>{[['oked','ОКЭД'],['activity','Вид деятельности'],['territory','Территория'],['employeesMin','Мин. работников'],['employeesMax','Макс. работников'],['payrollMin','Мин. ФОТ'],['payrollMax','Макс. ФОТ'],['salaryMin','Мин. средняя ЗП'],['salaryMax','Макс. средняя ЗП'],['taxesMin','Мин. налоги'],['taxesMax','Макс. налоги']].map(([key,label])=><Grid item xs={12} sm={6} key={key}><TextField fullWidth size="small" label={label} value={(draft as any)[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} type={key.includes('Min')||key.includes('Max')?'number':'text'}/></Grid>)}</Grid></DialogContent><DialogActions><Button onClick={reset}>Сбросить</Button><Button variant="contained" onClick={apply}>Применить</Button></DialogActions></Dialog>
    <Dialog open={relatedOpen} onClose={()=>setRelatedOpen(false)} maxWidth="xl" fullWidth><DialogTitle>Детализация: {relatedTitle}</DialogTitle><DialogContent><Typography color="text.secondary" sx={{mb:1}}>Показаны записи выбранного периода и территории. Это детализация, а не автоматическое заключение о компании.</Typography><Box sx={{overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['ОКЭД','ИИН/БИН','Наименование','Численность','ФОТ','Средняя ЗП','Налоги'].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:'1px solid #ddd'}}>{h}</th>)}</tr></thead><tbody>{related.map((r,i)=><tr key={r.id||i}><td style={{padding:8,borderBottom:'1px solid #eee'}}>{r['Код ОКЭД'] ?? '—'}</td><td style={{padding:8,borderBottom:'1px solid #eee'}}>{r['ИИН/БИН'] ? <Button size="small" onClick={()=>openCompany(String(r['ИИН/БИН']))}>{r['ИИН/БИН']}</Button> : '—'}</td>{['Наименование','Ср.числ','ФОТ','Ср.зп','Налоги'].map(k=><td key={k} style={{padding:8,borderBottom:'1px solid #eee'}}>{r[k] ?? '—'}</td>)}</tr>)}</tbody></table></Box></DialogContent><DialogActions><Button onClick={()=>setRelatedOpen(false)}>Закрыть</Button></DialogActions></Dialog>
    <Dialog open={companyOpen} onClose={()=>setCompanyOpen(false)} maxWidth="md" fullWidth><DialogTitle>Профиль компании</DialogTitle><DialogContent>{company&&<><Typography variant="h6" fontWeight={800}>{company.company?.name||'Без названия'}</Typography><Typography color="text.secondary">БИН/ИИН: {company.company?.bin}</Typography><Grid container spacing={2} sx={{my:1}}>{[['Риск',company.riskScore],['Работники',company.current?.employees],['ФОТ',company.current?.payroll],['Средняя ЗП',company.current?.averageSalary],['Налоги',company.current?.taxes]].map(([k,v])=><Grid item xs={6} sm={4} key={String(k)}><Paper sx={{p:1.5}}><Typography variant="caption" color="text.secondary">{k}</Typography><Typography fontWeight={800}>{formatMetric(v)}</Typography></Paper></Grid>)}</Grid><Typography fontWeight={800} sx={{mt:2}}>Сигналы</Typography>{company.riskFactors?.length?company.riskFactors.map((f:any)=><Alert key={f.code} severity={f.severity==='high'?'error':'warning'} sx={{mt:1}}>{f.message}</Alert>):<Alert severity="success">Критичных автоматических сигналов не обнаружено.</Alert>}{company.current?.warnings?.map((w:string)=><Alert key={w} severity="info">{w}</Alert>)}<HistoryCharts data={company.history||[]}/><Typography fontWeight={800} sx={{mt:2}}>Изменения к предыдущему периоду</Typography>{Object.entries(metricLabels).filter(([k])=>k!=='organizations').map(([k,label])=><Typography key={k}>{label}: {formatMetric(company.absoluteChanges?.[k]?.absolute)} / {formatMetric(company.absoluteChanges?.[k]?.percent)}{company.absoluteChanges?.[k]?.percent!=null?'%':''}</Typography>)}<Typography fontWeight={800} sx={{mt:2}}>История</Typography>{company.history?.map((h:any,i:number)=><Box key={i} sx={{py:1,borderBottom:'1px solid #eee'}}>{h.period||'Период не указан'} · работников {formatMetric(h.employees)} · ФОТ {formatMetric(h.payroll)}</Box>)}</>}</DialogContent><DialogActions><Button onClick={()=>setCompanyOpen(false)}>Закрыть</Button></DialogActions></Dialog>
  </Box>;
}
